# Generated by Django 2.2.12 on 2023-01-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Input/data')),
                ('Number', models.TextField(max_length=50)),
                ('status', models.TextField(max_length=50)),
            ],
        ),
    ]
